"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

export function Header(){
 const [account,setAccount]=useState<string|null>(null);
 async function connect(){const eth=(window as any).ethereum;if(!eth){setAccount("WALLET UNAVAILABLE");return}try{const a=await eth.request({method:"eth_requestAccounts"});setAccount(a?.[0]??null)}catch{setAccount(null)}}
 return <header className="topbar"><Link className="brand" href="/">PRIOR</Link><nav className="nav"><Link href="/live">Live</Link><Link href="/circuits">Circuits</Link><Link href="/history/demo">History</Link><Link href="/profile/demo">Profile</Link></nav><button className="wallet" onClick={connect}>{account?account.slice(0,6)+"…"+account.slice(-4):"Connect"}</button></header>
}

export function ProbabilityTrack({value,market,onChange,locked=false}:{value:number;market:number|null;onChange?:(n:number)=>void;locked?:boolean}){
 return <div className="control"><div className="track" aria-hidden="true"/><div className="eyebrow">0 <span style={{float:"right"}}>100</span></div><input aria-label="Forecast probability of Up" type="range" min="0" max="100" value={value} disabled={locked} onChange={e=>onChange?.(Number(e.target.value))}/><div className="eyebrow"><span className="amber">Market {market==null?"—":`${market}%`}</span><span className="blue" style={{float:"right"}}>You {value}%</span></div></div>
}

type LiveMarket={marketId:string;asset:string;intervalSec:number;expiry:string;clobStatus:string;lastPrice:string|null;binaryPoolAddress:string};
export function LiveCanvas(){
 const [markets,setMarkets]=useState<LiveMarket[]>([]); const [selected,setSelected]=useState<LiveMarket|null>(null); const [value,setValue]=useState(50); const [state,setState]=useState("UNAVAILABLE");
 useEffect(()=>{fetch("https://dev.smk.somnia.host/v1/graphql",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query:`query { Market(limit: 20, order_by: {createdAtBlock: desc}, where: {clobStatus: {_eq: "Trading"}}) { marketId asset intervalSec expiry clobStatus lastPrice binaryPoolAddress } }`})}).then(r=>r.json()).then(j=>{const rows=(j?.data?.Market??[]) as LiveMarket[];setMarkets(rows);setSelected(rows[0]??null);setState(rows.length?"LIVE":"NO TRADING MARKETS")}).catch(()=>setState("RPC / INDEXER UNAVAILABLE") )},[]);
 const marketValue=selected?.lastPrice==null?null:Math.round(Number(selected.lastPrice)/10000);
 return <><Header/><main className="shell"><aside className="rail"><div className="eyebrow">Markets / Shannon</div>{markets.map((m)=><button className={'market-row '+(selected?.marketId===m.marketId?'active':'')} key={m.marketId} onClick={()=>setSelected(m)}><strong>{m.asset} · {Number(m.intervalSec)/60}m</strong><br/><span className="amber">{m.lastPrice==null?"—":`${marketValue}% Up`}</span><br/><span className="mono">{m.clobStatus} · {m.marketId.slice(-6)}</span></button>)}{!markets.length&&<div className="state-note">{state}</div>}<div className="state-note"><div className="eyebrow">Active Circuit</div><br/>No authorized Circuit yet.<br/><br/><Link href="/circuits">Configure rules →</Link></div></aside><section className="canvas"><div className="canvas-head"><span>{selected?`${selected.asset} · ${Number(selected.intervalSec)/60} MIN`:"NO MARKET SELECTED"}</span><span className="amber">{selected?.clobStatus??state}</span></div>{selected?<><div className="focus"><div className="eyebrow">Market reference / Up · indexer last price</div><div className="prob-row"><div><div className="prob amber">{marketValue==null?"—":`${marketValue}%`}</div><div className="eyebrow">◆ MARKET</div></div><div><div className="prob blue">{value}%</div><div className="eyebrow">● YOU</div></div></div><ProbabilityTrack value={value} market={marketValue} onChange={setValue}/></div><div className="actions"><button className="primary commit" disabled>COMMIT REQUIRES LIVE WALLET FLOW</button></div><div className="state-note"><div className="eyebrow">Chain state</div><br/>Market data is live. Commitment is not shown until a confirmed RFT receipt exists.<br/><br/><span className="mono">CHAIN 50312 · MARKET ID {selected.marketId}</span></div></>:<div className="notice">{state}. No market evidence is fabricated.</div>}</section><aside className="rail right"><span className="context">DEPTH</span><span className="context">EXEC</span><span className="context">PROOF</span></aside></main></>
}
