import Link from "next/link";
import { findForecast, formatBps, OWNER, score } from "../../evidence";
import { EvidenceDrawer, ForecastNode, MarketNode, PriorHeader } from "../../components";

export default function ForecastPage({ params }: { params: { id: string } }) {
  const forecast = findForecast(params.id);
  if (!forecast) return <><PriorHeader/><main id="main" className="page-shell"><header className="page-heading"><span className="instrument-label">FORECAST · UNVERIFIED</span><h1>EVIDENCE, NOT HINDSIGHT.</h1><p>No accepted Forecast exists for this identifier. No resolution, score, hash, receipt, or market reference is shown.</p></header><Link className="secondary-button" href="/live">BACK TO LIVE</Link></main></>;
  const beat = forecast.marketScoreDelta !== null && forecast.marketScoreDelta > 0;
  return <><PriorHeader/><main id="main" className="forecast-page"><section className="forecast-analysis"><header className="evidence-header"><span>RESOLVED · FINALIZED</span><h1>{forecast.label} · {forecast.interval}</h1><p className="mono">FORECAST {forecast.trialId}</p></header><div className="analysis-confrontation"><div><span>YOUR FORECAST</span><ForecastNode locked/><strong className="forecast-color">{formatBps(forecast.forecastBps)} UP</strong></div><div><span>MARKET AT COMMIT</span><MarketNode/><strong className="market-color">{forecast.referenceBps === null ? "Unavailable" : `${formatBps(forecast.referenceBps)} UP`}</strong></div><div><span>OUTCOME</span><strong>{forecast.outcome}</strong></div></div><section className="score-block"><div><span>Forecast Brier</span><strong>{score(forecast.forecastBrier)}</strong></div><div><span>Market Brier</span><strong>{score(forecast.marketBrier)}</strong></div><div><span>Beat market baseline on this Forecast</span><strong>{forecast.marketScoreDelta === null ? "UNAVAILABLE" : beat ? "YES" : "NO"}</strong></div></section><section className="execution-block"><h2>ACTION</h2><dl><div><dt>Decision</dt><dd>{forecast.decision}</dd></div><div><dt>Order state</dt><dd>{forecast.orderStatus ?? "NOT REQUESTED"}</dd></div><div><dt>PnL</dt><dd>Not derived on this surface</dd></div></dl></section><section className="evidence-timeline"><h2>EVIDENCE TIMELINE</h2><ol><li><i>1</i><div><b>Forecast committed</b><span>{forecast.commitBlock ? `block ${forecast.commitBlock}` : "block not present in accepted artifact"}</span></div></li>{forecast.orderTx && <li><i>2</i><div><b>Order submitted and filled</b><span className="mono">{forecast.orderTx}</span></div></li>}<li><i>3</i><div><b>DreamDEX resolved {forecast.outcome}</b><span>external outcome</span></div></li><li><i>4</i><div><b>Forecast finalized</b><span>{forecast.finalizationBlock ? `block ${forecast.finalizationBlock}` : "block not present in accepted artifact"}</span></div></li></ol></section><EvidenceDrawer forecast={forecast}/></section><aside className="certificate-rail"><span className="wordmark">PRIOR</span><span>FORECAST</span><strong>{formatBps(forecast.forecastBps)}</strong><ForecastNode locked/><b>RESOLVED {forecast.outcome}</b><p>{forecast.label} · {forecast.interval}</p><dl className="mono"><div><dt>marketId</dt><dd>{forecast.marketId}</dd></div><div><dt>status</dt><dd>{forecast.status}</dd></div></dl><Link className="text-link" href={`/profile/${OWNER}`}>VIEW FORECASTER →</Link></aside></main></>;
}
