import { decodeFunctionData, decodeFunctionResult, encodeAbiParameters, encodeFunctionData, keccak256, parseTransaction, recoverTransactionAddress, type Hex } from "viem";
import { IntegrationError } from "../../../packages/agent-integration/src/index";
import { SHANNON_ADDRESSES, SHANNON_CHAIN_ID } from "./live-read";

const COMMIT_ABI = [{ type: "function", name: "commitForecast", inputs: [
  { name: "marketId", type: "bytes32" }, { name: "pUpBps", type: "uint16" },
  { name: "referenceUpBps", type: "uint16" }, { name: "referenceValid", type: "bool" },
  { name: "tradeTag", type: "uint64" }, { name: "actionIntent", type: "uint8" },
], outputs: [{ name: "trialId", type: "bytes32" }] }] as const;
const TRIAL_FOR_ABI = [{ type: "function", name: "trialFor", inputs: [{ name: "forecaster", type: "address" }, { name: "marketId", type: "bytes32" }], outputs: [{ name: "trialId", type: "bytes32" }] }] as const;

export interface ForecastCommitEnvelope { signedTransaction: string; expectedMarketId: string; }
export interface RpcWriter { rpc(method: string, params: unknown[]): Promise<unknown>; }
function hex(value: unknown, field: string): Hex { if (typeof value !== "string" || !/^0x[0-9a-fA-F]+$/.test(value)) throw new IntegrationError("MALFORMED_INPUT", `${field} must be a hex string`, 400); return value as Hex; }
function bytes32(value: unknown, field: string): Hex { const h = hex(value, field); if (h.length !== 66) throw new IntegrationError("MALFORMED_INPUT", `${field} must be bytes32`, 400); return h.toLowerCase() as Hex; }
function address(value: unknown, field: string): string { if (typeof value !== "string" || !/^0x[0-9a-fA-F]{40}$/.test(value)) throw new IntegrationError("MALFORMED_INPUT", `${field} must be an address`, 400); return value.toLowerCase(); }
function trialId(signer: string, marketId: Hex): Hex { return keccak256(encodeAbiParameters([{ type: "uint256" }, { type: "address" }, { type: "address" }, { type: "bytes32" }], [BigInt(SHANNON_CHAIN_ID), SHANNON_ADDRESSES.rftRegistry, signer as `0x${string}`, marketId])); }
async function existingTrial(writer: RpcWriter, signer: string, marketId: Hex): Promise<string> { const data = encodeFunctionData({ abi: TRIAL_FOR_ABI, functionName: "trialFor", args: [signer as `0x${string}`, marketId] }); const raw = await writer.rpc("eth_call", [{ to: SHANNON_ADDRESSES.rftRegistry, data }, "latest"]); if (typeof raw !== "string") throw new IntegrationError("UPSTREAM_MALFORMED", "RFT trialFor returned malformed data", 502); try { return decodeFunctionResult({ abi: TRIAL_FOR_ABI, functionName: "trialFor", data: raw as Hex }) as Hex; } catch { throw new IntegrationError("UPSTREAM_MALFORMED", "RFT trialFor did not match the verified ABI", 502); } }
async function receipt(writer: RpcWriter, txHash: string, signer: string): Promise<{ status: "INCLUDED" | "REVERTED" | "UNKNOWN"; receipt?: Record<string, unknown> }> { for (let attempt = 0; attempt < 10; attempt += 1) { const value = await writer.rpc("eth_getTransactionReceipt", [txHash]); if (value && typeof value === "object") { const r = value as Record<string, unknown>; if (r.transactionHash !== txHash || typeof r.blockNumber !== "string" || typeof r.blockHash !== "string" || r.to?.toString().toLowerCase() !== SHANNON_ADDRESSES.rftRegistry.toLowerCase()) throw new IntegrationError("UPSTREAM_MALFORMED", "receipt identity did not match the submitted RFT transaction", 502); const transaction = await writer.rpc("eth_getTransactionByHash", [txHash]); if (!transaction || typeof transaction !== "object") throw new IntegrationError("UPSTREAM_MALFORMED", "transaction readback was unavailable", 502); const t = transaction as Record<string, unknown>; if (t.hash !== txHash || t.to?.toString().toLowerCase() !== SHANNON_ADDRESSES.rftRegistry.toLowerCase() || t.from?.toString().toLowerCase() !== signer) throw new IntegrationError("READBACK_MISMATCH", "transaction readback identity did not match the signed transaction", 502); if (r.status === "0x1") return { status: "INCLUDED", receipt: r }; if (r.status === "0x0") return { status: "REVERTED", receipt: r }; throw new IntegrationError("UPSTREAM_MALFORMED", "receipt status is not recognized", 502); } await new Promise((resolve) => setTimeout(resolve, 250)); } return { status: "UNKNOWN" }; }

export async function submitSignedForecast(envelope: unknown, writer: RpcWriter): Promise<Record<string, unknown>> {
  if (!envelope || typeof envelope !== "object" || Array.isArray(envelope)) throw new IntegrationError("MALFORMED_INPUT", "submission must be an object", 400);
  const e = envelope as Record<string, unknown>; const raw = hex(e.signedTransaction, "signedTransaction"); const marketId = bytes32(e.expectedMarketId, "expectedMarketId");
  if (raw.length > 20002) throw new IntegrationError("PAYLOAD_TOO_LARGE", "signed transaction exceeds 10 KiB", 413);
  let tx: ReturnType<typeof parseTransaction>; try { tx = parseTransaction(raw); } catch { throw new IntegrationError("MALFORMED_INPUT", "signedTransaction is not a valid serialized transaction", 400); }
  if (tx.type !== "eip1559" || !tx.to || tx.to.toLowerCase() !== SHANNON_ADDRESSES.rftRegistry.toLowerCase()) throw new IntegrationError("TARGET_NOT_ALLOWED", "only EIP-1559 transactions to the Shannon RFT registry are relayable", 403);
  if (tx.chainId !== SHANNON_CHAIN_ID) throw new IntegrationError("CHAIN_MISMATCH", "signed transaction must target Somnia Shannon chainId 50312", 400);
  if (tx.value !== undefined && tx.value !== 0n) throw new IntegrationError("MALFORMED_INPUT", "commitForecast relay requires zero transaction value", 400);
  if (!tx.data) throw new IntegrationError("MALFORMED_INPUT", "signed transaction has no calldata", 400);
  let decoded: { functionName: string; args?: readonly unknown[] }; try { decoded = decodeFunctionData({ abi: COMMIT_ABI, data: tx.data }); } catch { throw new IntegrationError("TARGET_NOT_ALLOWED", "transaction calldata is not commitForecast", 403); }
  if (decoded.functionName !== "commitForecast" || !decoded.args || decoded.args.length !== 6 || String(decoded.args[0]).toLowerCase() !== marketId) throw new IntegrationError("IDENTITY_MISMATCH", "transaction calldata does not match expectedMarketId", 409);
  let signer: string; try { signer = (await recoverTransactionAddress({ serializedTransaction: raw as `0x02${string}` })).toLowerCase(); } catch { throw new IntegrationError("MALFORMED_INPUT", "signedTransaction signature could not be recovered", 400); }
  const chain = await writer.rpc("eth_chainId", []); if (String(chain).toLowerCase() !== "0x" + SHANNON_CHAIN_ID.toString(16)) throw new IntegrationError("CHAIN_MISMATCH", "configured RPC is not Somnia Shannon chainId 50312", 502);
  const existing = await existingTrial(writer, signer, marketId); if (existing !== (`0x${"0".repeat(64)}`)) return { status: "ALREADY_COMMITTED", chainId: SHANNON_CHAIN_ID, trialId: existing, marketId, forecaster: signer, custody: "CLIENT_SIGNED_NO_WORKER_KEY", broadcast: false };
  const txHash = await writer.rpc("eth_sendRawTransaction", [raw]); if (typeof txHash !== "string" || !/^0x[0-9a-fA-F]{64}$/.test(txHash)) throw new IntegrationError("UPSTREAM_MALFORMED", "RPC returned an invalid transaction hash", 502);
  const expectedTrialId = trialId(signer, marketId); const readback = await receipt(writer, txHash, signer); if (readback.status === "UNKNOWN") return { status: "UNKNOWN", chainId: SHANNON_CHAIN_ID, transactionHash: txHash, trialId: expectedTrialId, marketId, forecaster: signer, custody: "CLIENT_SIGNED_NO_WORKER_KEY", receipt: null };
  if (readback.status === "REVERTED") return { status: "REVERTED", chainId: SHANNON_CHAIN_ID, transactionHash: txHash, trialId: expectedTrialId, marketId, forecaster: signer, custody: "CLIENT_SIGNED_NO_WORKER_KEY", receipt: readback.receipt };
  const committed = await existingTrial(writer, signer, marketId); if (committed.toLowerCase() !== expectedTrialId.toLowerCase()) throw new IntegrationError("READBACK_MISMATCH", "receipt succeeded but trialFor did not return the expected trial ID", 502);
  return { status: "INCLUDED", chainId: SHANNON_CHAIN_ID, transactionHash: txHash, trialId: expectedTrialId, target: SHANNON_ADDRESSES.rftRegistry, function: "commitForecast", marketId, forecaster: signer, custody: "CLIENT_SIGNED_NO_WORKER_KEY", receipt: readback.receipt };
}
