export const runtime = "edge";

import Link from "next/link";
import { ACCEPTED_FORECASTS, CONTINUITY, CONTINUITY_ID, formatBps, short } from "../../evidence";
import hero from "../../../../../evidence/m4-3-live-zero-action-lifecycle.json";
import { CircuitTimeline, ForecastNode, MarketNode, PriorHeader } from "../../components";
import { ParticipantCircuitRoom } from "./ParticipantCircuitRoom";
const PARTICIPANT_MARKET_SENTINEL = `0x${"00".repeat(32)}`;

export default function CircuitPage({ params, searchParams }: { params: { id: string }; searchParams?: { marketId?: string } }) {
  const canonical = params.id.toLowerCase() === CONTINUITY_ID.toLowerCase();
  const heroCanonical = params.id.toLowerCase() === hero.circuitId.toLowerCase();
  if (heroCanonical) return <><PriorHeader/><main id="main" className="circuit-page"><header className="circuit-header"><div><span className="instrument-label">CIRCUIT CONTROL ROOM · V2 HERO EVIDENCE</span><h1>BTC · 1h · ZERO-ACTION PROOF</h1></div><div><span>SOURCE</span><strong>ARCHIVED EVIDENCE · LIVE SHANNON READBACK</strong><a className="text-link" href={`/api/continuity?circuitId=${hero.circuitId}&marketId=${hero.market.marketId}`}>OPEN LIVE CONTINUITY JSON →</a></div><div><span>FINAL STATE</span><strong>COMPLETE · processed=true</strong></div></header><div className="circuit-control"><section className="current-iteration"><header><span className="instrument-label">V2 CANONICAL ITERATION</span><b>MARKET · RESOLVED DOWN</b></header><div className="iteration-duel"><div><MarketNode/><span>MARKET</span><strong>DOWN</strong></div><div><ForecastNode locked/><span>FORECAST</span><strong>{formatBps(hero.forecast.probabilityUpBps)}</strong></div></div><dl className="iteration-rules"><div><dt>Market ID</dt><dd className="mono">{short(hero.market.marketId)}</dd></div><div><dt>Trial / RFT</dt><dd className="mono">{short(hero.trialId)}</dd></div><div><dt>Bound</dt><dd>true</dd></div><div><dt>Processed</dt><dd>true</dd></div><div><dt>Target windows</dt><dd>{hero.circuitIntent.targetWindows}</dd></div><div><dt>Economic authority</dt><dd>NONE</dd></div></dl><Link className="text-link" href={`/proof`}>OPEN CAUSAL PROOF →</Link></section><aside className="intent-rail"><details open><summary>CIRCUIT INTENT · LOCKED · V2</summary><div className="intent-tree"><b>BTC · 1H</b><span>├─ {hero.circuitIntent.targetWindows} target window</span><span>├─ owner {short(hero.owner)}</span><span>├─ budget {hero.circuitIntent.totalBudget}</span><span>├─ max / market {hero.circuitIntent.maxPerMarket}</span><span>└─ allowed actions {hero.circuitIntent.allowedActionsBitmap}</span></div></details></aside><aside className="execution-lane"><details open><summary>CONSEQUENCE</summary>{["FORECAST · AUTHENTICATED", "RFT · COMMITTED", "BINDING · CONFIRMED", "BUY_UP · ActionNotAllowed", "BUY_DOWN · ActionNotAllowed", "RFT · SCORED"].map((label,index)=><div className="causal-stage complete" key={label}><i>{index+1}</i><span>{label}</span></div>)}<p>No order, collateral, approval, or operator permission occurred.</p></details></aside></div><section className="continuity-band"><div className="band-heading"><span className="instrument-label">V2 FINAL READBACK</span><strong>Circuit ↔ market ↔ RFT · one canonical processed iteration</strong></div><div className="timeline-preview"><p>Outcome: <b>DOWN</b> · RFT score: <b>{hero.trialFinal.forecastBrier}</b> · Market reference: <b>UNAVAILABLE</b></p><Link className="secondary-button" href="/proof">VIEW FULL PROOF</Link></div></section></main></>;
  if (!canonical) {
    if (/^0x[0-9a-fA-F]{64}$/.test(params.id)) { const requestedMarket = searchParams?.marketId; const marketId = requestedMarket && /^0x[0-9a-fA-F]{64}$/.test(requestedMarket) ? requestedMarket : PARTICIPANT_MARKET_SENTINEL; return <><PriorHeader/><ParticipantCircuitRoom circuitId={params.id} marketId={marketId}/></>; }
    return <><PriorHeader/><main id="main" className="page-shell"><header className="page-heading"><span className="instrument-label">CIRCUIT · UNKNOWN</span><h1>NO ACCEPTED EVIDENCE</h1><p>This identifier is not present in the accepted evidence set. No state, receipt, or success is fabricated.</p></header><Link className="secondary-button" href="/circuits">BACK TO CIRCUITS</Link></main></>;
  }
  const current = ACCEPTED_FORECASTS[2];
  return <><PriorHeader/><main id="main" className="circuit-page">
    <header className="circuit-header"><div><span className="instrument-label">CIRCUIT CONTROL ROOM · ACCEPTED SNAPSHOT</span><h1>BTC · 5m · CIRCUIT 04</h1></div><div><span>STATUS AT BLOCK {CONTINUITY.block}</span><strong>ACTIVE THEN · NOT CLAIMED LIVE</strong></div><div><span>RUNNER RECOVERY · V1 SUPPORTING EVIDENCE</span><strong>RECONSTRUCTED · NO DUPLICATE RUNNER EFFECTS OBSERVED</strong></div></header>
    <div className="circuit-control">
      <section className="current-iteration"><header><span className="instrument-label">CURRENT ITERATION · LATEST ACCEPTED</span><b>MARKET 2 · RESOLVED</b></header><div className="iteration-duel"><div><MarketNode/><span>MARKET</span><strong>{formatBps(current.referenceBps!)}</strong></div><div><ForecastNode locked/><span>FORECAST</span><strong>{formatBps(current.forecastBps)}</strong></div></div><dl className="iteration-rules"><div><dt>Minimum margin</dt><dd>8 points</dd></div><div><dt>Available executable price</dt><dd>Unavailable in accepted artifact</dd></div><div><dt>Current decision</dt><dd>ABSTAIN</dd></div><div><dt>Outcome</dt><dd>{current.outcome}</dd></div></dl><Link className="text-link" href={`/forecast/${current.id}`}>OPEN FORECAST EVIDENCE →</Link></section>
      <aside className="intent-rail"><details open><summary>CIRCUIT INTENT · LOCKED</summary><div className="intent-tree"><b>BTC · 5M</b><span>├─ {CONTINUITY.immutableIntent.targetWindows} markets</span><span>├─ owner Forecast</span><span>├─ ≥ {CONTINUITY.immutableIntent.minMarginBps / 100}pt minimum margin</span><span>├─ {CONTINUITY.immutableIntent.maxPerMarket} raw max / market</span><span>├─ {CONTINUITY.immutableIntent.totalBudget} raw total</span><span>└─ allowed actions bitmap {CONTINUITY.immutableIntent.allowedActionsBitmap}</span></div><button type="button" className="secondary-button" disabled>PAUSE · WRITE UNAVAILABLE</button><button type="button" className="danger-button" disabled>STOP · WRITE UNAVAILABLE</button></details></aside>
      <aside className="execution-lane"><details open><summary>EXECUTION</summary>{["FORECAST · LOCKED", "POLICY · EVALUATED", "MARKET · RESOLVED", "DECISION · ABSTAIN", "ORDER · NOT REQUESTED", "RESULT · SCORED"].map((label, index) => <div className="causal-stage complete" key={label}><i>{index + 1}</i><span>{label}</span></div>)}<p>Autonomous execution remains BLOCKED_EXTERNAL. Runner activity is not execution success.</p></details></aside>
    </div>
    <section className="continuity-band"><div className="band-heading"><span className="instrument-label">CONTINUITY / TIMELINE</span><strong>same intent · distinct marketId · one canonical Forecast each</strong></div><CircuitTimeline/></section>
    <section className="trajectory"><header><span className="instrument-label">BELIEF OVER TIME</span><b>DERIVED VIEW, NOT CIRCUIT DEFINITION</b></header><div className="trajectory-row"><span>MARKET</span><i>◆</i><i>◆</i><i>○</i><i>○</i></div><div className="trajectory-row forecast-color"><span>FORECAST</span><i>●</i><i>●</i><i>○</i><i>○</i></div><div className="trajectory-row"><span>ACTION</span><i>—</i><i>—</i><i> </i><i> </i></div><div className="trajectory-row"><span>RESULT</span><i>✓</i><i>✓</i><i> </i><i> </i></div><div className="mono trajectory-id">{short(CONTINUITY_ID, 14, 12)}</div></section>
  </main></>;
}
